name: Secret Repository Workflow

on: 
  push:
    branches:
      - main  # Run workflow on push to 'main' branch
  pull_request:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Environment
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" > .env
          echo "SEARCH_API_KEY=${{ secrets.SEARCH_API_KEY }}" >> .env
          echo "SEARCH_ENGINE_ID=${{ secrets.SEARCH_ENGINE_ID }}" >> .env
        shell: bash

        
      - name: Check Environment Variables (Safe Debugging)
        run: printenv | grep "API_KEY"